version: "3.9"
networks:
  webapi-dev:

services:
  app:
    container_name: webapi-dev
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
      - "80:80"
    networks:
      - webapi-dev
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: web_db
    ports:
      - "15432:5432"
    networks: 
      - webapi-dev
    volumes:
      - postgres-data:/var/lin/postgresql/data
volumes: 
  postgres-data: